apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-deny
spec:
  baseOSExtensionsContainerImage: ''
  config:
    ignition:
      version: 3.2.0
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Rebooter

            [Service]
            Type=oneshot
            ExecStartPre=/usr/bin/sleep 2
            ExecStart=/sbin/reboot

            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: Rebooter.service