apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 7
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: nginx
        image: cpu-eater
        resources:
          requests:
            cpu: 50m
            memory: 0G
          limits:
            memory: 0G
        imagePullPolicy: Always
