apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 100
  priorityClassName: production-priority
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: nginx
        image: memory-eater
        resources:
          requests:
            cpu: 0m
            memory: 0G
          limits:
            cpu: 0m